**Conversões entre Arrays e Series:**

In [70]:
import pandas as pd
import numpy as np

In [71]:
#convertendo um array pra uma série:
arr1=np.array([10,20,30])
serie1=pd.Series(arr1)
print(arr1)
print(serie1)

[10 20 30]
0    10
1    20
2    30
dtype: int64


In [72]:
#convertendo uma série pra um array:
arr2=serie1.to_numpy()
print(arr2)

[10 20 30]


**Dataframes e suas Principais Funções:**

In [73]:
#criação:
arr3=np.array([[1,2],[3,4]])
df_arr=pd.DataFrame(arr3, columns=['A','B'])
print(arr3)
print(df_arr)

[[1 2]
 [3 4]]
   A  B
0  1  2
1  3  4


In [74]:
#transformando uma coluna em uma série:
coluna_serie=df_arr['A']
print(coluna_serie)

0    1
1    3
Name: A, dtype: int64


In [75]:
#contagem de valores:
estados=pd.DataFrame({'Cidade':['RJ','SP','MG','ES','RJ','RJ','SP']})
print(estados['Cidade'].value_counts())

Cidade
RJ    3
SP    2
MG    1
ES    1
Name: count, dtype: int64


In [76]:
#Cálculos Estatísticos:
notas=pd.DataFrame({'Notas':[2,4,6,8,10,12,12,12,14]})
print(notas['Notas'].sum()) #soma
print(notas['Notas'].mean()) #média
print(notas['Notas'].median()) #mediana
print(notas.describe()) #resumo das estatísticas

80
8.88888888888889
10.0
           Notas
count   9.000000
mean    8.888889
std     4.136558
min     2.000000
25%     6.000000
50%    10.000000
75%    12.000000
max    14.000000


**Atividades:**

Atividade 1:

Crie um array unidimensional com os números de 1 a 12. Transforme este array
em uma matriz de 3 linhas e 4 colunas.

(DESAFIO: Aplique a transposição da matriz para criar as dimensões em 4x3 (.transpose) e,
em seguida, crie um array unidimensional (.flatten)).

In [77]:
#Resolução:
array_original=np.arange(1,13)
print(array_original)
array_3_por_4=array_original.reshape(3,4)
print(array_3_por_4)
print('------------')
#DESAFIO:
array_4_por_3=array_3_por_4.transpose()
print(array_4_por_3)
array_unidimensional=array_4_por_3.flatten()
print(array_unidimensional)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[ 1  5  9  2  6 10  3  7 11  4  8 12]


Atividade 2 (GITHUB):

Leia o arquivo ClassicDisco.csv trabalhado em aulas anteriores e aplique o comando .describe()
para gerar uma análise estatística prévia dos dados. Não esqueça dos comandos para verificar as
primeiras e últimas linhas do dataset como apoio nessa atividade.

In [ ]:
##EXEMPLO DE LEITURA:
dados=pd.read_csv('blocos-sob-contrato-jan.csv')
print(dados.head())
estatistica=dados.describe()
print(estatistica)